version: '2'

services:
  frontier:
    image: squirrel
#    build: .
    hostname: frontier
    environment:
      - HOBBIT_RABBIT_HOST=rabbit
      - SEED_FILE=/var/squirrel/data/seeds.txt
#      - RDB_HOST_NAME=rethinkdb
#      - RDB_PORT=28015
    networks:
      - squirrel
    volumes:
      - ./data/frontier:/var/squirrel/data
    command: java -cp squirrel.jar org.hobbit.core.run.ComponentStarter org.aksw.simba.squirrel.components.FrontierComponent

  rethinkdb:
    image: rethinkdb
    networks:
      - squirrel
    hostname: rethinkdb

  # message bus
  rabbit:
    image: rabbitmq:management
    container_name: rabbit
    networks:
      - squirrel
    ports:
      - "8081:15672"
      # Forwarding the port for testing
      - "5672:5672"

  worker1:
    image: squirrel
#    build: .
    hostname: worker1
    environment:
      - HOBBIT_RABBIT_HOST=rabbit
      - OUTPUT_FOLDER=/var/squirrel/data
    networks:
      - squirrel
    volumes:
        - ./data/worker1:/var/squirrel/data
    command: java -cp squirrel.jar org.hobbit.core.run.ComponentStarter org.aksw.simba.squirrel.components.WorkerComponent

  worker2:
    image: squirrel
#    build: .
    hostname: worker2
    environment:
      - HOBBIT_RABBIT_HOST=rabbit
      - OUTPUT_FOLDER=/var/squirrel/data
    networks:
      - squirrel
    volumes:
        - ./data/worker2:/var/squirrel/data
    command: java -cp squirrel.jar org.hobbit.core.run.ComponentStarter org.aksw.simba.squirrel.components.WorkerComponent

  worker3:
    image: squirrel
#    build: .
    hostname: worker3
    environment:
      - HOBBIT_RABBIT_HOST=rabbit
      - OUTPUT_FOLDER=/var/squirrel/data
    networks:
      - squirrel
    volumes:
        - ./data/worker3:/var/squirrel/data
    command: java -cp squirrel.jar org.hobbit.core.run.ComponentStarter org.aksw.simba.squirrel.components.WorkerComponent

#  worker4:
#    build: .
#    hostname: worker4
#    networks:
#      - squirrel
#    volumes:
#        - ./data/worker4:/shared
#    command: start-worker.sh 4 tcp://frontier:60000 /shared

#  worker5:
#    build: .
#    hostname: worker5
#    networks:
#      - squirrel
#    volumes:
#        - ./data/worker5:/shared
#    command: start-worker.sh 5 tcp://frontier:60000 /shared

#  seedgenerator:
#    build: .
#    hostname: seedgenerator
#    networks:
#      - squirrel
#    volumes:
#        - ./data/seedgenerator:/shared
#    links:
#        - frontier
#    command: start-seed-generator.sh tcp://frontier:60000

#  seedgeneratorlodstats:
#    build: .
#    hostname: seedgeneratorlodstats
#    networks:
#      - squirrel
#    links:
#        - frontier
#    command: start-seed-generator-lodstats.sh tcp://frontier:60000

networks:
  squirrel:

